Updating Event Class
soundata/soundata pull request #115
Opened 2023-03-31 20:38 UTC by harshpalan

Updating Event Class to accommodate changes from PR [61](https://github.com/soundata/soundata/pull/61) for Spatial Events. Now Event Class contains all the required attributes for Spatial Events.

2023-04-14 22:17 UTC, magdalenafuentes requested changes
Hey @harshpalan this is looking great, just a few more things and we merge:
- Azimuth, elevation and distance descriptions in function readme are missing
- There's line 370 not being tested
- See my comments below about checking distances in coordinates

2023-04-14 22:17 UTC, magdalenafuentes commented on soundata/annotations.py
> +        validate_lengths_equal([azimuth, elevation, distance, cartesian_coord])
Let's add intervals here to impose coherence

2023-04-14 22:17 UTC, magdalenafuentes commented on soundata/annotations.py
> +        validate_azimuth(elevation, elevation_unit, allow_none=True)
Is this right? Is because the limits are the same?

2023-04-14 22:17 UTC, magdalenafuentes commented on soundata/annotations.py
> +        )
Let's check for distances>0 inside coordinates as well

2023-04-14 22:17 UTC, magdalenafuentes commented on soundata/annotations.py
> +        azimuth (np.ndarray or None):
Missing description on azimuth, elevation and distance

2023-04-14 22:17 UTC, magdalenafuentes commented on soundata/annotations.py
> +        raise ValueError(
We're not testing this line

2023-04-21 20:19 UTC, harshpalan commented on soundata/annotations.py
> +        validate_azimuth(elevation, elevation_unit, allow_none=True)
Added a new function validation function for elevation.

2023-04-28 17:40 UTC, magdalenafuentes approved these changes

2023-04-28 17:40 UTC, magdalenafuentes commented on soundata/annotations.py
> +        if any([a < -2 * np.pi for a in elevation]) or any(
Should be `pi/2`

2023-04-28 17:40 UTC, merged