[WIP] Adding loader for TUT Sound events 2017
soundata/soundata pull request #37
Opened 2021-03-18 17:46 UTC by pzinemanas

### [WIP] Adding loader for TUT Sound events 2017

We still have to complete the Clip.to_jams() function.

### Description

Please include the following information at the top level docstring for the dataset's module mydataset.py:

- [x] Describe annotations included in the dataset
- [x] Indicate the total duration of the dataset in hours, and (optionally) also list the number of individual files
- [x] Mention the origin of the dataset (e.g. creator, institution)
- [x] Describe the type of audio included in the dataset
- [x] Indicate any relevant papers related to the dataset
- [x] Include a description about how the data can be accessed and the license it uses (if applicable)

#### Dataset loaders checklist:

- [x] Create a script in `scripts/`, e.g. `make_my_dataset_index.py`, which generates an index file.
- [x] Run the script on the canonical version of the dataset and save the index in `soundata/indexes/` e.g. `my_dataset_index.json`.
- [x] Create a module in soundata, e.g. `soundata/my_dataset.py`
- [x] Create tests for your loader in `tests/`, e.g. `test_my_dataset.py`
- [x] Add your module to `docs/source/soundata.rst` and `docs/source/quick_reference.rst`
- [x] Run `tests/test_full_dataset.py` on your dataset.

#### TODOs
- [ ] Complete Clip.to_jams() function.
- [ ] Add test_to_jams() function.

2021-03-19 20:42 UTC, justinsalamon commented
Awesome progress @pzinemanas ! Let us know when it's ready for a code review :)

2021-03-20 12:16 UTC, pzinemanas commented
I think you can start reviewing it (@magdalenafuentes @justinsalamon). To finish the loader I think we have to adapt the [`jams_converter`](https://github.com/soundata/soundata/blob/4a9e1239893447d661ff070e02b83e075f47f47a/soundata/jams_utils.py#L12) function (related to #7).

2021-03-23 14:55 UTC, magdalenafuentes requested changes
@pzinemanas Fantastic PR! Just left minor comments, let me know if something's not clear!

2021-03-23 14:55 UTC, magdalenafuentes commented on docs/source/soundata.rst
> +.. automodule:: soundata.datasets.tut_sound_events_2017
nit: maybe call it `tut_2017` or `tut_se` or something with less `_`?

2021-03-23 14:55 UTC, magdalenafuentes commented on soundata/datasets/tut_sound_events_2017.py
> +"""
Super good summary!

2021-03-23 14:55 UTC, magdalenafuentes commented on soundata/datasets/tut_sound_events_2017.py
> +from soundata import io
do all imports from the same package in the same line

2021-03-23 14:55 UTC, magdalenafuentes commented on soundata/datasets/tut_sound_events_2017.py
> +LICENSE_INFO = "TUT License."
Maybe add a link to the license as well?

2021-03-23 14:55 UTC, magdalenafuentes commented on soundata/datasets/tut_sound_events_2017.py
> +        # TODO: add events
@justinsalamon looking at the [JAMS namespace](https://jams.readthedocs.io/en/stable/namespace.html#scaper) it seems to me that we could use `Blob` to host `Events`? What do you think? Other option could be to do a PR in the `JAMS` repo but that would take longer. I'm inclined for `blobs` at the moment if we don't see any semantic issue

2021-03-23 14:55 UTC, magdalenafuentes commented on soundata/datasets/tut_sound_events_2017.py
> +        return load_audio(*args, **kwargs)
The idea of exposing the functions at the dataset level is for the user to be able to use the load functions directly if needed. For that to be complete add here the `load_events` the same way you added the `load_audio`

2021-03-23 14:55 UTC, magdalenafuentes commented on tests/datasets/test_tut_sound_events_2017.py
> +    assert audio.shape[1] == 88200  # Check audio duration is as expected
can you trim the audio to 1s? as the library groes we want to keep the `test/resources` folder as small as possible

2021-03-23 14:55 UTC, magdalenafuentes commented on tests/resources/sound_datasets/tut_sound_events_2017/TUT-sound-events-2017-development/evaluation_setup/street_fold1_evaluate.txt
> +audio/street/b099.wav	street	0.186989	2.558792	car
trim this file to a few lines (e.g. 5)

2021-03-23 14:55 UTC, magdalenafuentes commented on tests/resources/sound_datasets/tut_sound_events_2017/TUT-sound-events-2017-development/evaluation_setup/street_fold1_train.txt
> +audio/street/b094.wav	street	1.505533	3.493229	car
trim this one to a few lines as well

2021-03-23 14:55 UTC, magdalenafuentes commented on tests/resources/sound_datasets/tut_sound_events_2017/TUT-sound-events-2017-development/evaluation_setup/street_fold2_evaluate.txt
> +audio/street/b009.wav	street	2.509522	17.005812	car
same

2021-03-23 14:55 UTC, magdalenafuentes commented on tests/resources/sound_datasets/tut_sound_events_2017/TUT-sound-events-2017-development/evaluation_setup/street_fold2_train.txt
> +audio/street/b094.wav	street	1.505533	3.493229	car
same this one

2021-03-23 14:55 UTC, magdalenafuentes commented on tests/resources/sound_datasets/tut_sound_events_2017/TUT-sound-events-2017-development/evaluation_setup/street_fold3_evaluate.txt
> +audio/street/b095.wav	street	0.0	2.462242	car
✂️

2021-03-23 14:55 UTC, magdalenafuentes commented on tests/resources/sound_datasets/tut_sound_events_2017/TUT-sound-events-2017-development/evaluation_setup/street_fold3_train.txt
> +audio/street/b094.wav	street	1.505533	3.493229	car
✂️

2021-03-23 14:55 UTC, magdalenafuentes commented on tests/resources/sound_datasets/tut_sound_events_2017/TUT-sound-events-2017-development/evaluation_setup/street_fold4_evaluate.txt
> +audio/street/a128.wav	street	0.0	4.359811	large vehicle
✂️

2021-03-23 14:55 UTC, magdalenafuentes commented on tests/resources/sound_datasets/tut_sound_events_2017/TUT-sound-events-2017-development/evaluation_setup/street_fold4_train.txt
> +audio/street/b093.wav	street	3.794935	110.64771	people walking
✂️

2021-03-23 14:55 UTC, magdalenafuentes commented on tests/resources/sound_datasets/tut_sound_events_2017/TUT-sound-events-2017-evaluation/evaluation_setup/street_evaluate.txt
> +audio/street/a011.wav	street	0.0	0.856625	people speaking
Just out of curiosity: do you need all these files here for testing?

2021-03-23 14:55 UTC, magdalenafuentes commented on tests/resources/sound_datasets/tut_sound_events_2017/TUT-sound-events-2017-evaluation/evaluation_setup/street_evaluate.txt
> +audio/street/a011.wav	street	0.0	0.856625	people speaking
also ✂️

2021-03-23 15:04 UTC, pzinemanas commented on docs/source/soundata.rst
> +.. automodule:: soundata.datasets.tut_sound_events_2017
The problem here is that we have several TUT databases for acoustic scenes and sound events and from different years:
Maybe tut_se_2017? Then we should follow the same format: tut_as_2017, tut_se_2016, etc.

2021-03-23 15:06 UTC, pzinemanas commented on tests/datasets/test_tut_sound_events_2017.py
> +    assert audio.shape[1] == 88200  # Check audio duration is as expected
Yes!

2021-03-23 16:17 UTC, magdalenafuentes commented on docs/source/soundata.rst
> +.. automodule:: soundata.datasets.tut_sound_events_2017
`tut2017_se`? I just don't like so many `_` XD

2021-03-23 18:44 UTC, pzinemanas commented on docs/source/soundata.rst
> +.. automodule:: soundata.datasets.tut_sound_events_2017
In this case, it could be `tut2017se` but it sounds a bit cryptic to me.

2021-03-24 21:30 UTC, justinsalamon commented on soundata/datasets/tut_sound_events_2017.py
> +"""
+1

2021-03-24 21:37 UTC, justinsalamon commented on soundata/datasets/tut_sound_events_2017.py
> +        # TODO: add events
`blob` is a little too generic, per offline discussion with @magdalenafuentes sounds like `segment_open` is a better alternative :)

2021-03-24 21:37 UTC, justinsalamon approved these changes
LGTM too @pzinemanas (pending jams converter)

2021-03-24 21:57 UTC, pzinemanas commented on soundata/datasets/tut_sound_events_2017.py
> +        # TODO: add events
Yes, see #43

2021-03-25 16:23 UTC, magdalenafuentes approved these changes
@pzinemanas looks great to me! Feel free to merge :)

2021-03-25 16:23 UTC, magdalenafuentes commented on soundata/datasets/tut2017se.py
> +            events=self.events,
:D

2021-03-25 17:02 UTC, merged